version: "3.4"

services:
  aiohttp:
    build:
      context: ./aiohttp
    volumes:
      - ./aiohttp/src:/app/src
    ports:
      - "8000:8000"
    expose:
      - "8000"
  nginx:
    build:
      context: ./nginx
    ports:
      - "8080:80"
    expose:
      - "80"