version: "3.4"

services:
  aiohttp:
    build:
      context: ./aiohttp
    volumes:
      - ./aiohttp/src:/app/src
    ports:
      - "8000:8000"
      - "8001:8001"
    expose:
      - "8000"
      - "8001"